#pragma kernel NoiseVolume

#include "Packages/com.arycama.webglnoiseunity/Noise.hlsl"

float _Octaves, _Frequency;
RWTexture3D<float> Result;

[numthreads(8, 8, 8)]
void NoiseVolume(uint3 id : SV_DispatchThreadID)
{
	float3 size;
	Result.GetDimensions(size.x, size.y, size.z);
	
	float result = SimplexNoise((id / size) / _Frequency);
	
	Result[id] = result * 0.5 + 0.5;
	//Result[id] = pnoise(id / size, _Frequency);
}