#pragma kernel Upsample
#pragma kernel Upsample BICUBIC

#include "Packages/com.arycama.noderenderpipeline/ShaderLibrary/Utility.hlsl"

RWTexture2D<float4> Result;
Texture2D<float4> Input;
float4 ScaleOffset, TexelSize;

[numthreads(8, 8, 1)]
void Upsample(uint2 id : SV_DispatchThreadID)
{
	float2 uv = id * ScaleOffset.xy + ScaleOffset.zw;
	Result[id] = Input.SampleLevel(_LinearClampSampler, uv, 0.0);
}